### ISSUE TITLE
Install make error: implicit declaration of function in mc_con.c

### ISSUE THREAD

**Issue by matthew-lowery** [LiyrAstroph/MICA2#2]
$ make                                                                                                                                             [13:36:37]
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/main.o src/main.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/allvars.o src/allvars.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/system.o src/system.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/run.o src/run.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/dnest_con.o src/dnest_con.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/dnest_line.o src/dnest_line.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/read.o src/read.c
mpicc -O2 -Wall -finline-functions -I/opt/homebrew/Cellar/gsl/2.7/include  -I/usr/include/lapacke -fgnu89-inline -Wno-deprecated -g -I/opt/homebrew/Cellar/mpich/3.4.3/include  -I /Users/mattlowery/Desktop/code/astro/CDNest    -c -o src/mc_con.o src/mc_con.c
src/mc_con.c:245:5: error: implicit declaration of function 'dnest_get_posterior_sample_file' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    dnest_get_posterior_sample_file(posterior_sample_file);
    ^
src/mc_con.c:426:22: warning: unused variable 'sign' [-Wunused-variable]
  int i, j, k, info, sign, *ipiv;
                     ^
1 warning and 1 error generated.
make: *** [src/mc_con.o] Error 1

**Comment by liyropt** [comment]
Thanks for posting the error.
It seems that the error is raised because the compiler did not find an explicit definition for the function "dnest_get_posterior_sample_file()".  This function is provided by the external library "CDNest (libdnest.so;  a diffusive nested sampling library)", so you may want to check whether "libdnest.so" is explicitly specified in "Makefile". An example:
##########
DNEST_INCL  = -I/Users/mattlowery/Desktop/code/astro/CDNest
DNEST_LIBS  = -L/Users/mattlowery/Desktop/code/astro/CDNest -ldnest
##########

Besides,  to run MICA2,  the path to the library should also be added to the environmental variable, e.g., edit the ".bashrc" file to add
##########
export LD_LIBRARY_PATH=/Users/mattlowery/Desktop/code/astro/CDNest:$LD_LIBRARY_PATH
##########

Hope these solve your problem. If it remains, please let me know. Thanks again.

**Comment by mwl10** [comment]
Thanks for your prompt response.
The libdnest.so file was generated w/o error:
#############
mattlowery:CDNest/ (mpich) $ ls                                                                                                                                                [14:45:55]
Makefile         build            docs             libdnest.so.dSYM setup.cfg        src
README.rst       dnest.h          libdnest.so      python           setup.py         tests
############
I added the export statement to my .bashrc file, and I had added those lines to my Makefile previously. The same error persists.
[Makefile.txt](https://github.com/LiyrAstroph/MICA2/files/7756102/Makefile.txt)

**Comment by matthew-lowery** [comment]
Thank you for your prompt response. I'm now getting the error:

ld: file not found: @rpath/libgcc_s.1.1.dylib for architecture arm64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mica2] Error 1
#################################
Yet I know that file is located in this directory:

(base) mattlowery:11/ (master) $ pwd                                                  [17:03:11]
/opt/homebrew/Cellar/gcc/11.2.0/lib/gcc/11
(base) mattlowery:11/ (master) $ ls                                                   [17:03:19]
gcc                 libgfortran.a       libitm.a            libssp.dylib
libatomic.1.dylib   libgfortran.dylib   libitm.dylib        libssp_nonshared.a
libatomic.a         libgfortran.spec    libitm.spec         libstdc++.6.dylib
libatomic.dylib     libgomp.1.dylib     libobjc-gnu.4.dylib libstdc++.a
libcc1.0.so         libgomp.a           libobjc-gnu.a       libstdc++.a-gdb.py
libcc1.so           libgomp.dylib       libobjc-gnu.dylib   libstdc++.dylib
libgcc_s.1.1.dylib  libgomp.spec        libssp.0.dylib      libstdc++fs.a
libgfortran.5.dylib libitm.1.dylib      libssp.a            libsupc++.a
##################
So I'm not sure how to link it. My Makefile:
[makefile.txt](https://github.com/LiyrAstroph/MICA2/files/7756936/makefile.txt)

Thank you again!

**Comment by liyropt** [comment]
To link gcc library, in Makefile add a line like 
########
GCC_LIBS = -L /opt/homebrew/Cellar/gcc/11.2.0/lib/gcc/11 -lgcc
########
and add "GCC_LIBS" to "LIBS" as 
########
LIBS     = $(GSL_LIBS) $(LAPACK_LIBS) $(MPICHLIB) $(DNEST_LIBS) $(FFTW_LIBS) $(GCC_LIBS)
########

But it seems to me that the underlying problem might be that you used clang-based MPICC to compile some required packages and gcc-based MPICC to compile some others, leading to a missing link to gcc library. In Linux, the command "MPICC" can automatically link gcc library. Not sure about Mac system.  Anyway, it is better to compile all packages using a consistent compiler. 

BTW, did you install CDNest smoothly? It also uses MPICC. To check with the installation, cd to the subdirectory "CDNest/tests/" and run some testing cases, such as 
########
mpiexec -n 3 ./dnest 1
########
(see more [here](https://cdnest.readthedocs.io/en/latest/tests.html))

**Comment by matthew-lowery** [comment]
switching to use on linux
